apiVersion: v2
name: geodini
description: A Helm chart for the Geodini application
type: application
version: 0.3.0
appVersion: "0.3.0"

dependencies:
  - name: redis
    version: "18.19.4"
    repository: "https://charts.bitnami.com/bitnami"
